[package]
name = "multiharp_toolkit"
version = "0.1.0"
edition = "2021"

[lib]
name = "_mhtk_rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cli"

[dependencies]
arrow = "54.2.0"
chrono = "0.4.39"
nom = "7.1.3"
parquet = "54.2.0"
pyo3 = "0.20.0"

[build-dependencies]
bindgen = "0.69.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "raw_stream_benchmark"
harness = false

[features]
extension-module = ["pyo3/extension-module"]
stub = []
default = ["extension-module"]
