[package]
name = "multiharp_toolkit"
version = "0.1.0"
edition = "2021"

[lib]
name = "_mhtk_rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cli"

[dependencies]
pyo3 = "0.20.0"
nom = "7.1.3"
chrono = "0.4.31"

[build-dependencies]
bindgen = "0.69.1"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
