[project]
name = "multiharp-toolkit"
version = "0.1.1"
description = "Add your description here"
authors = [{ name = "zigen", email = "hrlclb@gmail.com" }]
dependencies = [
    "pyarrow>=14.0.1",
    "kaleido>=0.2.1",
    "pandas>=2.1.2",
    "polars>=0.20.3",
    "plotly>=5.18.0",
    "maturin>=1.4.0",
]
readme = "README.md"
requires-python = ">= 3.11"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.scripts]
calc-g2 = "multiharp_toolkit.calc_g2:main"

[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[tool.rye]
managed = true
dev-dependencies = [
    "ipykernel>=6.26.0",
    "nbformat>=5.9.2",
    "pytest>=7.4.4",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.sdist]
exclude = [
  ".vemv",
  ".gitignore",
  "sampledata",
  "result"
]

[tool.maturin]
module-name = "multiharp_toolkit._mhtk_rs"
features = ["pyo3/extension-module"]
python-source = "src"
