[project]
name = "mh-file-parser"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "zigen", email = "hrlclb@gmail.com" }]
dependencies = [
    "pyarrow>=14.0.1",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pandas>=2.1.2",
    "polars>=0.19.12",
    "matplotlib>=3.8.0",
    "ipykernel>=6.26.0",
    "plotly>=5.18.0",
    "nbformat>=5.9.2",
]

[tool.hatch.metadata]
allow-direct-references = true
