[project]
name = "multiharp-toolkit"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "zigen", email = "hrlclb@gmail.com" }]
dependencies = [
    "pyarrow>=14.0.1",
    "kaleido>=0.2.1",
    "pandas>=2.1.2",
    "polars>=0.19.12",
    "plotly>=5.18.0",
]
readme = "README.md"
requires-python = ">= 3.11"

[project.scripts]
calc-g2 = "multiharp_toolkit.calc_g2:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ipykernel>=6.26.0",
    "nbformat>=5.9.2",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.sdist]
exclude = [
  ".vemv",
  ".gitignore",
  "sampledata",
  "result"
]

