[package]
name = "multiharp_toolkit_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "multiharp_toolkit_rs"
crate-type = ["cdylib"]

[dependencies]
bindgen = "0.69.1"
pyo3 = "0.19.0"
